#!/usr/bin/env python3
"""
density_profile_average.py

Average density profiles generated by the LAMMPS ``fix ave/chunk`` command
over a user-defined range of frames.

Features
--------
- Reads LAMMPS density profile files.
- Averages profiles over multiple frames.
- Allows selecting the starting frame or starting timestep.
- Writes the averaged density profile to a text file.

Author: Samuel Blázquez Fernández
"""

import argparse
import sys

import numpy as np


# ==========================================
# Helper functions
# ==========================================

def try_parse_header(line: str):
    """
    Try to parse a LAMMPS block header.

    Expected format:
        timestep  number_of_bins  total_count

    Returns
    -------
    tuple or None
        (timestep, number_of_bins, total_count) if the line is a valid header,
        otherwise None.
    """
    stripped = line.strip()

    if not stripped or stripped.startswith("#"):
        return None

    parts = stripped.split()

    if len(parts) != 3:
        return None

    try:
        timestep = int(float(parts[0]))
        number_of_bins = int(float(parts[1]))
        total_count = int(float(parts[2]))
        return timestep, number_of_bins, total_count

    except ValueError:
        return None


# ==========================================
# Main program
# ==========================================

def main():
    parser = argparse.ArgumentParser(
        description=(
            "Average LAMMPS fix ave/chunk density profiles over multiple frames."
        )
    )

    parser.add_argument(
        "infile",
        help="Input density profile file generated by LAMMPS fix ave/chunk."
    )

    parser.add_argument(
        "-o",
        "--output",
        default="density_average.txt",
        help="Output file for the averaged density profile."
    )

    parser.add_argument(
        "--start-frame",
        type=int,
        default=0,
        help="Start averaging from this frame index. Default: 0."
    )

    parser.add_argument(
        "--start-timestep",
        type=int,
        default=None,
        help=(
            "Start averaging from the first block with timestep greater than "
            "or equal to this value."
        )
    )

    args = parser.parse_args()

    distances = None
    sum_density = None
    nframes_used = 0
    frame_idx = 0

    with open(args.infile, "r", encoding="utf-8", errors="replace") as file:
        while True:
            header = None

            for line in file:
                header = try_parse_header(line)
                if header is not None:
                    break

            if header is None:
                break

            timestep, number_of_bins, total_count = header

            block_distances = np.empty(number_of_bins, dtype=float)
            block_density = np.empty(number_of_bins, dtype=float)

            for bin_idx in range(number_of_bins):
                line = file.readline()

                if not line:
                    raise RuntimeError(
                        f"Unexpected end of file while reading timestep "
                        f"{timestep} with {number_of_bins} bins."
                    )

                line = line.strip()

                while not line or line.startswith("#"):
                    line = file.readline()

                    if not line:
                        raise RuntimeError(
                            f"Unexpected end of file while reading timestep "
                            f"{timestep}."
                        )

                    line = line.strip()

                parts = line.split()

                if len(parts) < 4:
                    raise RuntimeError(
                        f"Malformed line at timestep {timestep}, "
                        f"bin {bin_idx + 1}:\n{line}"
                    )

                # LAMMPS fix ave/chunk output:
                # column 1 -> bin index
                # column 2 -> coordinate
                # column 4 -> density/mass or selected averaged quantity
                block_distances[bin_idx] = float(parts[1])
                block_density[bin_idx] = float(parts[3])

            use_this_frame = True

            if frame_idx < args.start_frame:
                use_this_frame = False

            if (
                args.start_timestep is not None
                and timestep < args.start_timestep
            ):
                use_this_frame = False

            if use_this_frame:
                if distances is None:
                    distances = block_distances.copy()
                    sum_density = block_density.copy()

                else:
                    if number_of_bins != distances.size:
                        raise RuntimeError(
                            f"Number of bins changed from {distances.size} "
                            f"to {number_of_bins} at timestep {timestep}."
                        )

                    if not np.allclose(
                        block_distances,
                        distances,
                        atol=1e-6,
                        rtol=0,
                    ):
                        max_difference = float(
                            np.max(np.abs(block_distances - distances))
                        )

                        print(
                            f"Warning: density axis differs at timestep "
                            f"{timestep} "
                            f"(maximum absolute difference = "
                            f"{max_difference:.3e}). "
                            f"The axis from the first selected block will be used.",
                            file=sys.stderr,
                        )

                    sum_density += block_density

                nframes_used += 1

            frame_idx += 1

    if nframes_used == 0:
        raise RuntimeError(
            "No frames were selected. Check --start-frame or --start-timestep."
        )

    average_density = sum_density / nframes_used

    output_data = np.column_stack([distances, average_density])

    header = (
        f"# distance  density_avg   "
        f"(averaged over {nframes_used} frames; "
        f"start_frame={args.start_frame}, "
        f"start_timestep={args.start_timestep})"
    )

    np.savetxt(
        args.output,
        output_data,
        fmt="%.6f %.10e",
        header=header,
    )

    print(
        f"Successfully averaged {nframes_used} frames "
        f"(out of {frame_idx} total). "
        f"Output written to '{args.output}'."
    )


if __name__ == "__main__":
    main()
